int* criaVet(int pos, int val);
int* criaVetAl(int n);
int** criaMat(int lin, int col, int val);
char* strCopy(char* s);
char* sub1(char* s, int inicio, int fim);
char* sub2(char* s, int indice);
int compara_int(void* a, void* b);
int compara_double(void* a, void* b);
int compara_string(void* a, void* b);
int* intercala1(int* v1, int tamV1, int* v2, int tamV2);
void intercala2(int* vetor, int delimitador, int tamVetor);
void imprime_string(char* s);
int comprimento_string(char* s);
void copia_string(char* destino, char* origem);
